spring.config.activate.on-profile: dev
spring:
  application:
    name: app-template-dev
  datasource:
    url: jdbc:postgresql://postgres:5432/app_template_dev
  jpa:
    show-sql: true
    properties:
      format_sql: true