spring.config.activate.on-profile: dev
spring:
  application:
    name: app-template-dev
  jpa:
    show-sql: true
    properties:
      format_sql: true
management:
  endpoint:
    shutdown:
      enabled: true