server:
  port: 8000
  servlet:
    context-path: /
spring:
  devtools:
    add-properties: false
  main:
    banner-mode: off
  modulith:
    detection-strategy: explicitly-annotated
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
#      schema: app
      idle-timeout: 10000
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: HikariCP
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-root.yaml
#    default-schema: app
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

otel.traces.exporter: otlp
otel.metrics.exporter: otlp
otel.logs.exporter: otlp
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level) %logger{36} - %msg%n"
otel:
  exporter:
    otlp:
      traces:
        endpoint: http://otel-collector:4318/v1/traces
      metrics:
        endpoint: http://otel-collector:4318/v1/metrics
      logs:
        endpoint: http://otel-collector:4318/v1/logs