networks:
  default:
    driver: bridge
    name: prod
  observability:
    external: true
  data:
    external: true
services:
  backend:
    image: project-base/app:${project-version}
    restart: unless-stopped
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - "8080:8000"
    networks:
      - observability
      - data