networks:
  default:
    driver: bridge
    name: dev
  observability:
    external: true
  data:
    external: true
services:
  backend:
    image: project-base/app:${project-version}
    restart: unless-stopped
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8000:8000"
    networks:
      - observability
      - data