networks:
  observability:
    external: true
  data:
    external: true
  default:
    driver: bridge
    name: ${default-network}
services:
  app-template-dev:
    container_name: app-template-dev
    image: project-base/${project-name}:${project-version}
    restart: unless-stopped
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8000:8000"
    networks:
      - observability
      - data